import mongoose from "mongoose";
import dotenv from "dotenv";
import Card from "./src/models/Card";

dotenv.config();

const MONGODB_URI = "mongodb+srv://pokemon:pokemon2025~~@cluster0.py0v7jr.mongodb.net/pokemonDB?retryWrites=true&w=majority&appName=Cluster0";

const cards = [
  {
    cardName: "파이리",
    cardType: "fire",
    attack: 10,
    hp: 25,
    image2D: "/images/fireTier1.png",
    image3DColor: "/models/fireTier1_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "포니타",
    cardType: "fire",
    attack: 40,
    hp: 100,
    image2D: "/images/fireTier2.png",
    image3DColor: "/models/fireTier2_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "부스터",
    cardType: "fire",
    attack: 70,
    hp: 175,
    image2D: "/images/fireTier3.png",
    image3DColor: "/models/fireTier3_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "윈디",
    cardType: "fire",
    attack: 110,
    hp: 275,
    image2D: "/images/fireTier4.png",
    image3DColor: "/models/fireTier4_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "초염몽",
    cardType: "fire",
    attack: 150,
    hp: 375,
    image2D: "/images/fireTier5.png",
    image3DColor: "/models/fireTier5_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "리자몽",
    cardType: "fire",
    attack: 200,
    hp: 500,
    image2D: "/images/fireTier6.png",
    image3DColor: "/models/fireTier6_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "레시라무",
    cardType: "fire",
    attack: 300,
    hp: 750,
    image2D: "/images/fireTier7.png",
    image3DColor: "/models/fireTier7_color.glb",
    image3DGray: "/images/default_gray.png",
  },

  {
    cardName: "꼬부기",
    cardType: "water",
    attack: 10,
    hp: 25,
    image2D: "/images/waterTier1.png",
    image3DColor: "/models/waterTier1_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "고라파덕",
    cardType: "water",
    attack: 40,
    hp: 100,
    image2D: "/images/waterTier2.png",
    image3DColor: "/models/waterTier2_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "샤미드",
    cardType: "water",
    attack: 70,
    hp: 175,
    image2D: "/images/waterTier3.png",
    image3DColor: "/models/waterTier3_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "라프라스",
    cardType: "water",
    attack: 110,
    hp: 275,
    image2D: "/images/waterTier4.png",
    image3DColor: "/models/waterTier4_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "갸라도스",
    cardType: "water",
    attack: 150,
    hp: 375,
    image2D: "/images/waterTier5.png",
    image3DColor: "/models/waterTier5_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "거북왕",
    cardType: "water",
    attack: 200,
    hp: 500,
    image2D: "/images/waterTier6.png",
    image3DColor: "/models/waterTier6_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "가이오가",
    cardType: "water",
    attack: 300,
    hp: 750,
    image2D: "/images/waterTier7.png",
    image3DColor: "/models/waterTier7_color.glb",
    image3DGray: "/images/default_gray.png",
  },

  {
    cardName: "이상해씨",
    cardType: "forest",
    attack: 10,
    hp: 25,
    image2D: "/images/forestTier1.png",
    image3DColor: "/models/forestTier1_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "모다피",
    cardType: "forest",
    attack: 40,
    hp: 100,
    image2D: "/images/forestTier2.png",
    image3DColor: "/models/forestTier2_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "리피아",
    cardType: "forest",
    attack: 70,
    hp: 175,
    image2D: "/images/forestTier3.png",
    image3DColor: "/models/forestTier3_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "나시",
    cardType: "forest",
    attack: 110,
    hp: 275,
    image2D: "/images/forestTier4.png",
    image3DColor: "/models/forestTier4_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "토대부기",
    cardType: "forest",
    attack: 150,
    hp: 375,
    image2D: "/images/forestTier5.png",
    image3DColor: "/models/forestTier5_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "이상해꽃",
    cardType: "forest",
    attack: 200,
    hp: 500,
    image2D: "/images/forestTier6.png",
    image3DColor: "/models/forestTier6_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "세레비",
    cardType: "forest",
    attack: 300,
    hp: 750,
    image2D: "/images/forestTier7.png",
    image3DColor: "/models/forestTier7_color.glb",
    image3DGray: "/images/default_gray.png",
  },

  {
    cardName: "플러쉬",
    cardType: "electric",
    attack: 10,
    hp: 25,
    image2D: "/images/electricTier1.png",
    image3DColor: "/models/electricTier1_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "라이츄",
    cardType: "electric",
    attack: 40,
    hp: 100,
    image2D: "/images/electricTier2.png",
    image3DColor: "/models/electricTier2_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "전룡",
    cardType: "electric",
    attack: 70,
    hp: 175,
    image2D: "/images/electricTier3.png",
    image3DColor: "/models/electricTier3_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "자포코일",
    cardType: "electric",
    attack: 110,
    hp: 275,
    image2D: "/images/electricTier4.png",
    image3DColor: "/models/electricTier4_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "볼트로스",
    cardType: "electric",
    attack: 150,
    hp: 375,
    image2D: "/images/electricTier5.png",
    image3DColor: "/models/electricTier5_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "피카츄",
    cardType: "electric",
    attack: 200,
    hp: 500,
    image2D: "/images/electricTier6.png",
    image3DColor: "/models/electricTier6_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "썬더",
    cardType: "electric",
    attack: 300,
    hp: 750,
    image2D: "/images/electricTier7.png",
    image3DColor: "/models/electricTier7_color.glb",
    image3DGray: "/images/default_gray.png",
  },

  {
    cardName: "찌르꼬",
    cardType: "fly",
    attack: 10,
    hp: 25,
    image2D: "/images/flyTier1.png",
    image3DColor: "/models/flyTier1_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "깨비참",
    cardType: "fly",
    attack: 40,
    hp: 100,
    image2D: "/images/flyTier2.png",
    image3DColor: "/models/flyTier2_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "구구",
    cardType: "fly",
    attack: 70,
    hp: 175,
    image2D: "/images/flyTier3.png",
    image3DColor: "/models/flyTier3_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "깨비드릴조",
    cardType: "fly",
    attack: 110,
    hp: 275,
    image2D: "/images/flyTier4.png",
    image3DColor: "/models/flyTier4_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "무장조",
    cardType: "fly",
    attack: 150,
    hp: 375,
    image2D: "/images/flyTier5.png",
    image3DColor: "/models/flyTier5_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "토네로스",
    cardType: "fly",
    attack: 200,
    hp: 500,
    image2D: "/images/flyTier6.png",
    image3DColor: "/models/flyTier6_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "루기아",
    cardType: "fly",
    attack: 300,
    hp: 750,
    image2D: "/images/flyTier7.png",
    image3DColor: "/models/flyTier7_color.glb",
    image3DGray: "/images/default_gray.png",
  },

  {
    cardName: "꾸꾸리",
    cardType: "ice",
    attack: 10,
    hp: 25,
    image2D: "/images/iceTier1.png",
    image3DColor: "/models/iceTier1_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "메꾸리",
    cardType: "ice",
    attack: 40,
    hp: 100,
    image2D: "/images/iceTier2.png",
    image3DColor: "/models/iceTier2_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "빙큐보",
    cardType: "ice",
    attack: 70,
    hp: 175,
    image2D: "/images/iceTier3.png",
    image3DColor: "/models/iceTier3_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "얼음귀신",
    cardType: "ice",
    attack: 110,
    hp: 275,
    image2D: "/images/iceTier4.png",
    image3DColor: "/models/iceTier4_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "크레베이이스",
    cardType: "ice",
    attack: 150,
    hp: 375,
    image2D: "/images/iceTier5.png",
    image3DColor: "/models/iceTier5_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "레지아이스",
    cardType: "ice",
    attack: 200,
    hp: 500,
    image2D: "/images/iceTier6.png",
    image3DColor: "/models/iceTier6_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "프리져",
    cardType: "ice",
    attack: 300,
    hp: 750,
    image2D: "/images/iceTier7.png",
    image3DColor: "/models/iceTier7_color.glb",
    image3DGray: "/images/default_gray.png",
  },

  {
    cardName: "톱치",
    cardType: "land",
    attack: 10,
    hp: 25,
    image2D: "/images/landTier1.png",
    image3DColor: "/models/landTier1_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "코코리",
    cardType: "land",
    attack: 40,
    hp: 100,
    image2D: "/images/landTier2.png",
    image3DColor: "/models/landTier2_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "히포포타스",
    cardType: "land",
    attack: 70,
    hp: 175,
    image2D: "/images/landTier3.png",
    image3DColor: "/models/landTier3_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "대코파스",
    cardType: "land",
    attack: 110,
    hp: 275,
    image2D: "/images/landTier4.png",
    image3DColor: "/models/landTier4_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "맘모꾸리",
    cardType: "land",
    attack: 150,
    hp: 375,
    image2D: "/images/landTier5.png",
    image3DColor: "/models/landTier5_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "한카리아스",
    cardType: "land",
    attack: 200,
    hp: 500,
    image2D: "/images/landTier6.png",
    image3DColor: "/models/landTier6_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "그란돈",
    cardType: "land",
    attack: 300,
    hp: 750,
    image2D: "/images/landTier7.png",
    image3DColor: "/models/landTier7_color.glb",
    image3DGray: "/images/default_gray.png",
  },

  {
    cardName: "부우부",
    cardType: "normal",
    attack: 10,
    hp: 25,
    image2D: "/images/normalTier1.png",
    image3DColor: "/models/normalTier1_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "하데리어",
    cardType: "normal",
    attack: 40,
    hp: 100,
    image2D: "/images/normalTier2.png",
    image3DColor: "/models/normalTier2_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "다부니",
    cardType: "normal",
    attack: 70,
    hp: 175,
    image2D: "/images/normalTier3.png",
    image3DColor: "/models/normalTier3_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "해피너스",
    cardType: "normal",
    attack: 110,
    hp: 275,
    image2D: "/images/normalTier4.png",
    image3DColor: "/models/normalTier4_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "링곰",
    cardType: "normal",
    attack: 150,
    hp: 375,
    image2D: "/images/normalTier5.png",
    image3DColor: "/models/normalTier5_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "켄타로스",
    cardType: "normal",
    attack: 200,
    hp: 500,
    image2D: "/images/normalTier6.png",
    image3DColor: "/models/normalTier6_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "레지기가스",
    cardType: "normal",
    attack: 300,
    hp: 750,
    image2D: "/images/normalTier7.png",
    image3DColor: "/models/normalTier7_color.glb",
    image3DGray: "/images/default_gray.png",
  },

  {
    cardName: "아보",
    cardType: "poison",
    attack: 10,
    hp: 25,
    image2D: "/images/poisonTier1.png",
    image3DColor: "/models/poisonTier1_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "니드리나",
    cardType: "poison",
    attack: 40,
    hp: 100,
    image2D: "/images/poisonTier2.png",
    image3DColor: "/models/poisonTier2_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "독개굴",
    cardType: "poison",
    attack: 70,
    hp: 175,
    image2D: "/images/poisonTier3.png",
    image3DColor: "/models/poisonTier3_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "펜드라",
    cardType: "poison",
    attack: 110,
    hp: 275,
    image2D: "/images/poisonTier4.png",
    image3DColor: "/models/poisonTier4_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "니드킹",
    cardType: "poison",
    attack: 150,
    hp: 375,
    image2D: "/images/poisonTier5.png",
    image3DColor: "/models/poisonTier5_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "독침붕",
    cardType: "poison",
    attack: 200,
    hp: 500,
    image2D: "/images/poisonTier6.png",
    image3DColor: "/models/poisonTier6_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "무한다이노",
    cardType: "poison",
    attack: 300,
    hp: 750,
    image2D: "/images/poisonTier7.png",
    image3DColor: "/models/poisonTier7_color.glb",
    image3DGray: "/images/default_gray.png",
  },

  {
    cardName: "과사삭벌레",
    cardType: "worm",
    attack: 10,
    hp: 25,
    image2D: "/images/wormTier1.png",
    image3DColor: "/models/wormTier1_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "두루지벌레",
    cardType: "worm",
    attack: 40,
    hp: 100,
    image2D: "/images/wormTier2.png",
    image3DColor: "/models/wormTier2_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "케터피",
    cardType: "worm",
    attack: 70,
    hp: 175,
    image2D: "/images/wormTier3.png",
    image3DColor: "/models/wormTier3_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "실쿤",
    cardType: "worm",
    attack: 110,
    hp: 275,
    image2D: "/images/wormTier4.png",
    image3DColor: "/models/wormTier4_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "파라섹트",
    cardType: "worm",
    attack: 150,
    hp: 375,
    image2D: "/images/wormTier5.png",
    image3DColor: "/models/wormTier5_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "핫삼",
    cardType: "worm",
    attack: 200,
    hp: 500,
    image2D: "/images/wormTier6.png",
    image3DColor: "/models/wormTier6_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "게노세크트",
    cardType: "worm",
    attack: 300,
    hp: 750,
    image2D: "/images/wormTier7.png",
    image3DColor: "/models/wormTier7_color.glb",
    image3DGray: "/images/default_gray.png",
  },

  {
    cardName: "요가랑",
    cardType: "esper",
    attack: 10,
    hp: 25,
    image2D: "/images/esperTier1.png",
    image3DColor: "/models/esperTier1_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "랄토스",
    cardType: "esper",
    attack: 40,
    hp: 100,
    image2D: "/images/esperTier2.png",
    image3DColor: "/models/esperTier2_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "에브이",
    cardType: "esper",
    attack: 70,
    hp: 175,
    image2D: "/images/esperTier3.png",
    image3DColor: "/models/esperTier3_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "고디모아젤",
    cardType: "esper",
    attack: 110,
    hp: 275,
    image2D: "/images/esperTier4.png",
    image3DColor: "/models/esperTier4_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "가디안",
    cardType: "esper",
    attack: 150,
    hp: 375,
    image2D: "/images/esperTier5.png",
    image3DColor: "/models/esperTier5_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "뮤",
    cardType: "esper",
    attack: 200,
    hp: 500,
    image2D: "/images/esperTier6.png",
    image3DColor: "/models/esperTier6_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "뮤츠",
    cardType: "esper",
    attack: 300,
    hp: 750,
    image2D: "/images/esperTier7.png",
    image3DColor: "/models/esperTier7_color.glb",
    image3DGray: "/images/default_gray.png",
  },

  {
    cardName: "디아루가",
    cardType: "legend",
    attack: 400,
    hp: 1000,
    image2D: "/images/legendTier1.png",
    image3DColor: "/models/legendTier1_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "펄기아",
    cardType: "legend",
    attack: 400,
    hp: 1000,
    image2D: "/images/legendTier2.png",
    image3DColor: "/models/legendTier2_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "기라티나",
    cardType: "legend",
    attack: 400,
    hp: 1000,
    image2D: "/images/legendTier3.png",
    image3DColor: "/models/legendTier3_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "제크로무",
    cardType: "legend",
    attack: 400,
    hp: 1000,
    image2D: "/images/legendTier4.png",
    image3DColor: "/models/legendTier4_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "큐레무",
    cardType: "legend",
    attack: 400,
    hp: 1000,
    image2D: "/images/legendTier5.png",
    image3DColor: "/models/legendTier5_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "레쿠자",
    cardType: "legend",
    attack: 400,
    hp: 1000,
    image2D: "/images/legendTier6.png",
    image3DColor: "/models/legendTier6_color.glb",
    image3DGray: "/images/default_gray.png",
  },
  {
    cardName: "아르세우스",
    cardType: "legend",
    attack: 400,
    hp: 1000,
    image2D: "/images/legendTier7.png",
    image3DColor: "/models/legendTier7_color.glb",
    image3DGray: "/images/default_gray.png",
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("MongoDB connected");

    // 기존 카드 데이터 모두 삭제
    await Card.deleteMany({});
    console.log("Existing cards deleted");

    // 카드 데이터 삽입
    await Card.insertMany(cards);
    console.log("Seed data inserted");

    await mongoose.disconnect();
    console.log("MongoDB disconnected");
  } catch (error) {
    console.error("Error seeding data:", error);
  }
}

seed();
